# Generated by Django 5.2.14 on 2026-05-06 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("software", "Software & SaaS"),
                            ("equipment", "Equipment"),
                            ("travel", "Travel"),
                            ("meals", "Meals & Entertainment"),
                            ("office", "Office Supplies"),
                            ("rent", "Rent"),
                            ("utilities", "Utilities"),
                            ("professional", "Professional Services"),
                            ("marketing", "Marketing"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("invoice_date", models.DateField()),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("card", "Card"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Expenses",
                "ordering": ["-invoice_date"],
            },
        ),
    ]
