# Generated by Django 6.0.5 on 2026-05-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_igst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
