# Generated by Django 5.2.14 on 2026-05-06 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=6)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("pan", models.CharField(blank=True, max_length=10)),
                ("is_gst_registered", models.BooleanField(default=False)),
                ("tds_applicable", models.BooleanField(default=False)),
                (
                    "tds_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        help_text="TDS rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "tds_section",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 194J for professional services",
                        max_length=20,
                    ),
                ),
                (
                    "payment_terms",
                    models.PositiveIntegerField(
                        default=30, help_text="Payment terms in days"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Clients",
                "ordering": ["name"],
            },
        ),
    ]
